### ISSUE TITLE
youtube-dl no longer works on namesake website

### ISSUE THREAD

**Issue by Sushiman42** [Tzahi12345/YoutubeDL-Material#237]
No surprise here, but using this (and youtube-dl in general) no longer works on youtube. Probably a recent change. 

Error looks like: `ERROR: Unable to extract JS player URL`.

**Comment by Tzahi12345** [comment]
Hm I just started getting this error. I even tried youtube-dlc and it failed with the same error. Looks like it has been fixed with [youtube-dlc](https://github.com/blackjack4494/yt-dlc/issues/67), but the update hasn't been released yet it seems. In the meantime, I'm working on getting youtube-dlc support online (see #234)

**Comment by Sushiman42** [comment]
Quick update, youtube-dl.org pushed a new update today,  I believe it addresses the problems with youtube support. 

`https://youtube-dl.org/downloads/latest/youtube-dl-2020.11.01.1.tar.gz`

**Comment by 8bitgentleman** [comment]
New to youtubedl-material as of today and running into this issue. Is there something I need to do within the youtube-dl-material UI to update to the latest youtube-dl?

**Comment by Tzahi12345** [comment]
I just pushed out a hotfix which should fix this issue -- basically, youtube-dlc is now used by default. Once there's a new repo up for youtube-dl, it will then updates will be possible. But without the repo, it's impossible to know whether an update is available or not (the only alternative is always updating on startup, which seems like a big price to pay imo)

@8bitgentleman If you can test this I'd appreciate it! Just pull the latest `nightly` and see if it works.

**Comment by 8bitgentleman** [comment]
@Tzahi12345 `nightly` changes seem to work for me! Only hiccup are that downloaded .mp4 files won't play with quicktime even though VLC plays them just fine

**Comment by Tzahi12345** [comment]
@8bitgentleman That indicates that the file isn't actually a mp4 and is instead webm (VLC will play mislabeled file types, QuickTime will not), that problem has come up before, but it has been fixed so I'm curious where this is from. Can test out both youtube-dl and youtube-dlc (go to the Advanced tab in the settings to change it), and see if it only exists in one downloader and not the other?

**Comment by Sushiman42** [comment]
@Tzahi12345 `nightly` seems to be acting a little funky with some UI errors and logs breaking. No way to delete playlists.

My startup logs look like this:

```
2020-11-02T03:59:09.373Z INFO: youtube-dl successfully updated!
2020-11-02T03:59:09.386Z INFO: YoutubeDL-Material v4.1 started on PORT 17442
2020-11-02T03:59:09.398Z ERROR: 
```

And then there's just blank space where following log events should be.

**Comment by 8bitgentleman** [comment]
@Tzahi12345 Switched to youtube-dl to test and the issue still exists

**Comment by Tzahi12345** [comment]
@8bitgentleman can you set the log mode to verbose and see what args are being used? might help find exactly where the error is.

It should include `--merge-output-format,mp4` in there, which forces the file to come out as an mp4.

**Comment by 8bitgentleman** [comment]
@Tzahi12345 Sure, here's the log output
```
2020-11-02T23:49:58.825Z VERBOSE: youtube-dl args being used: -o,users/admin/video/%(title)s.mp4,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail
```

**Comment by Sushiman42** [comment]
Just a quick update, youtube-dl is back up on github.
