### ISSUE TITLE
Error: Cannot find module 'axios'

### ISSUE THREAD

**Issue by BasWeg** [Tzahi12345/YoutubeDL-Material#273]
Hi, 
I've just fetched the latest docker nightly build and now the docker is not starting due to following error:
`Error: Cannot find module 'axios'
Require stack:
- /app/twitch.js
- /app/app.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/app/twitch.js:2:13)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/app/app.js:30:18)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/app/twitch.js', '/app/app.js' ]
}`

best regards and thanks for this great tool 🥇

**Comment by Tzahi12345** [comment]
Ah this is my fault, last night I pushed an update and I forgot to update the backend dependencies to reflect the changes. In about an hour the build should be fixed, thanks for letting me know! Let me know if you run into any other issues :)

[Relevant commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/b0acb6312322b4f0a976655cd210c41bd7b02c45)

**Comment by ArtJames** [comment]
Hi,
The problem still exists.
Arm/v7 build from ~3 hours ago.

**Comment by Tzahi12345** [comment]
@ArtJames That is... weird! The problem existed because I forgot to push the updated package.json which basically lists out dependencies, so axios was missing as a result. When you pull does it say image is up to date?

**Comment by ArtJames** [comment]
It wasn't an update. It was the first pull on a fresh system.
Latest Raspi-OS with a fresh docker install.

image: tzahi12345/youtubedl-material:nightly

**Comment by Tzahi12345** [comment]
@ArtJames Right, I was just wondering if when you try pulling again if it says you're on the latest `nightly`

**Comment by ArtJames** [comment]
I just removed everything including volumes, and pulled it again.
Now it works.
Sorry for the inconvenience, and thanks for your quick response.

**Comment by Tzahi12345** [comment]
No problem! Glad it's working for you :)

I'll try not to forget to commit the dependencies next time lol
