### ISSUE TITLE
How to delete files from the webui when the source files are deleted?

### ISSUE THREAD

**Issue by miguelarios** [Tzahi12345/YoutubeDL-Material#307]
I am trying to just use youtubedl-material to download youtube videos, but i noticed that when you delete the source files there is still a thumbnail icon (with no thumbnail image) present and I can't erase it. How do I get videos that don't have sources files present?

**Comment by GldRush98** [comment]
I'm seeing problems deleting too.  Deleting via the gui doesn't seem to actually do anything. The icon disappears from the gui, but the back end video files are still there and if I reload the gui page, the icon for the video comes right back...

**Comment by Tzahi12345** [comment]
Just a quick question, does this only happen when you search a video and try to delete a video that's been manually deleted? I discovered a bug here, but it won't persist on refresh meaning it has been deleted, but it just stays in the UI until a reload.

I just want to make sure this is the same bug, or if you guys are experiencing a second one.

**Comment by GldRush98** [comment]
https://user-images.githubusercontent.com/7459955/104112711-00741600-52b8-11eb-8fd0-aff2df03e879.mp4

I'm not sure how to explain all of it so here's a screen recording.
I start off downloading a new youtube video. 
I show the new files downloaded via youtubedl.
I then try and delete the video.  The wrong thumbnail disappears, but after a reload the right video is now gone in the gui. So good right? Not so fast...
When I flip back to the file manager and you can see the downloaded files are still there and not deleted.
I reload the youtubedl page one more time to make sure it's not there...
So then I restart the docker container to load everything fresh.
I show the files are still there, not deleted.
I then finally go back to the youtubedl page and reload it after restarting the container, and guess what... the video is back! I try to delete it again and the wrong thumbnail disappears again, repeat ad nauseam.

The only way I have been able to actually delete anything is:
1) Stop the container
2) Manually remove the entry from db.json
3) Manually remove the downloaded files
4) Start the container

**Comment by Tzahi12345** [comment]
>edit: And I just realized there is a slight nsfw thumbnail on my youtubedl page. Sorry about that LOL

Haha you're good, sometimes users have issues downloading videos from... certain websites so I'm used to it

>I then finally go back to the youtubedl page and reload it after restarting the container, and guess what... the video is back! I try to delete it again and the wrong thumbnail disappears again, repeat ad nauseam.

This is actually a "feature" -- it's so facilitate rebuilding someone's database if it's been corrupted/deleted, and for a subscription's videos to be added if the container is stopped mid-retrieval.

I did apply a few fixes related to the "My videos" section that (at least) fixed the issue where the wrong file card got deleted. Do you mind switching to the latest `nightly` to see if this issue still exists? Quite strange though that the video never actually deletes in the file system, I haven't seen this issue before.

**Comment by miguelarios** [comment]
So for it's a bit different. I enter a link then download the video but after if I move or delete the files where they are saved to and refresh my web page the thumbnail is broken and I can't remove it. 

Even if I restart my container.

**Comment by GldRush98** [comment]
I switched to nightly on my container and it's still behaving the same way; wrong file card is removed, reload and the right one is now gone, the files never get removed.

@miguelarios You are deleting files with out deleting them in the gui, so that behavior is expected.  You should just use the gui for management (but I am not having much luck with that either).

**Comment by Tzahi12345** [comment]
@miguelarios so that specific issue should be fixed in the latest nightly

@GldRush98 Are you using multi-user mode? Any error/warning log messages? Trying to track down where this issue occurs.

**Comment by Tzahi12345** [comment]
I tracked down the bug! It was only in single-user mode and it was an easy fix. I pushed the changes and so the `nightly`, `latest`, and `4.2` tags should have those pushed in about an hour, let me know if it's actually fixed!

**Comment by GldRush98** [comment]
I just updated. So the wrong file card is still removed, however the files are actually being deleted now! Getting closer :)

**Comment by Tzahi12345** [comment]
Alright, hopefully this is fixed for good. I simplified the file card deletion process as I was doing some fancy stuff to save microseconds of performance but it was clearly giving me more trouble than it's worth. The `nightly`, `latest`, and `4.2` tags should be updated in about an hour with those fixes, let me know if these bugs are finally gone!

**Comment by GldRush98** [comment]
You sir, are a gentleman and a scholar. Updated my latest container and it is all working! Right card removed, files removed, everything. Thanks so much, and I really enjoy the ease of use your container brings to youtube-dl.

**Comment by miguelarios** [comment]
> @miguelarios so that specific issue should be fixed in the latest nightly.

@GldRush98 - while i understand the intended use is to use the GUI to manage the files but if i delete the source files and i still see a thumbnail in the webGUI regardless of whether the source files are present or not i would imagine that clicking the meatball icon and then delete should delete it from the frontend. This is at least my expectation.

Hey @Tzahi12345 i switched to the nightly fix and i still see the thumbnail artifact in the webUI. See this GIF.

![2021-01-11 10 57 33](https://user-images.githubusercontent.com/24581058/104213572-10950e00-53fc-11eb-8b04-2906ce98894e.gif)

**Comment by GldRush98** [comment]
Yeah, I mean obviously it should handle that condition and just remove the card / the entry from the db file.

**Comment by miguelarios** [comment]
I mean even if it doesn't do it automatically if i can at least click delete and it deletes the thumbnail it be fine.

**Comment by Tzahi12345** [comment]
>Hey @Tzahi12345 i switched to the nightly fix and i still see the thumbnail artifact in the webUI. See this GIF.

@miguelarios 

Wow, another bug! That's like 3 already. Anyways I found the issue and fixed it, all 3 tags should be updated in an hour, you know the drill. There's a lesson in here about not having proper tests (I do it manually and it's mostly in multi-user mode). I think that solves the bug that spawned this issue, I'll go ahead and close it but if it doesn't work I'll gladly reopen.

>You sir, are a gentleman and a scholar. Updated my latest container and it is all working! Right card removed, files removed, everything. Thanks so much, and I really enjoy the ease of use your container brings to youtube-dl.

@GldRush98 

"She had a very low voice... probably a smoker."

It's a pleasure! If you see any other bugs or have any suggestions, please feel free to open up an issue :)
