### ISSUE TITLE
[BUG] ERROR: /usr/bin/env: 'python': No such file or directory in Docker container

### ISSUE THREAD

**Issue by tehniemer** [Tzahi12345/YoutubeDL-Material#596]
**Describe the bug**
All subscriptions fail with the following errors
```
2022-05-03T01:39:14.999Z ERROR: /usr/bin/env: 'python': No such file or directory
2022-05-03T01:39:15.001Z ERROR: Subscribe: Failed to get subscription info. Subscribe failed.
```

**To Reproduce**
1. Spin up a new container
2. Add a subscription or playlist
3. See error

**Expected behavior**
Python exists and subscriptions work.

**Environment**
Installation details:
Installed version: v4.2 -   You are up to date.
Installation type: docker
Docker tag: nightly
Commit hash: 05ea5a8
Build date: 2022-05-02

**Comment by GlassedSilver** [comment]
Please try the current nightly, yours is outdated already. (the past few days have been really fast moving on the repo :) )

**Comment by tehniemer** [comment]
Pulled the latest nightly and now it's a no start condition
```
 1: 0x7f57431343cc node::Abort() [/lib/x86_64-linux-gnu/libnode.so.72]
 2: 0x7f574313445b  [/lib/x86_64-linux-gnu/libnode.so.72]
 3: 0x7f57431b6de2 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/lib/x86_64-linux-gnu/libnode.so.72]
 4: 0x7f57431b6f16 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/lib/x86_64-linux-gnu/libnode.so.72]
 5: 0x7f57430ff2c8 node::InitializeOncePerProcess(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]
 6: 0x7f57430ff4ac node::Start(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]
 7: 0x7f574266dd90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f574266de40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x5615698300f5 _start [node]
node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
```

**Comment by makzdot** [comment]
I'm having the same issue (running tag:latest) this is what fixed it for me.....for now:

#Go into the container:
docker exec -it ytdl-material /bin/bash

cd /usr/bin/
ln -s python3 python

**Comment by jonathanm-ur** [comment]
> I'm having the same issue (running tag:latest) this is what fixed it for me.....for now:
> 
> #Go into the container: docker exec -it ytdl-material /bin/bash
> 
> cd /usr/bin/ ln -s python3 python

How do you do that if the container won't stay running? I'm seeing the same thing as @tehniemer , 

`node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x1466eb43d3cc node::Abort() [/lib/x86_64-linux-gnu/libnode.so.72]`

**Comment by GlassedSilver** [comment]
> > I'm having the same issue (running tag:latest) this is what fixed it for me.....for now:
> > #Go into the container: docker exec -it ytdl-material /bin/bash
> > cd /usr/bin/ ln -s python3 python
> 
> How do you do that if the container won't stay running? I'm seeing the same thing as @tehniemer ,
> 
> `node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed. 1: 0x1466eb43d3cc node::Abort() [/lib/x86_64-linux-gnu/libnode.so.72]`

They are on the ancient latest tag... (irony, I know, but when 4.3 releases, it will be the new latest image and we can all go back to nightlies for on-the-edge users and latest for everyone who wants stable, tested and less features straight from the oven. :D)

I do not recommend going back to latest though, instead a new nightly build that hopefully works a lot better will be issued tonight. :)

**Comment by GlassedSilver** [comment]
I'll link the PR which should fix it. Once the PR merges this will be closed and marked as resolved.

Should you continue to see this issue on the THEN most recent build in the nightly-branch please do not hesitate to comment here, and we will re-open and re-investigate.

Hope you have a wonderful week so far and let's hope this is finally checked off. :)

**Comment by tehniemer** [comment]
Looks like a new nightly was pushed an hour ago, I pulled it and the same issue is still present.

**Comment by GlassedSilver** [comment]
Which architecture are you on?

**Comment by tehniemer** [comment]
Docker is running in Debian 11

**Comment by Tzahi12345** [comment]
I was able to reproduce the issue, working on a fix! Will most likely be @makzdot's solution of `ln -s` somewhere in the Dockerfile.

**Comment by Tzahi12345** [comment]
Should be fixed now! `ln -s` method worked great, thanks @tehniemer for the report and @makzdot for the solution!

@jonathanm-ur Do you still see the crash with the latest `nightly`?

**Comment by tehniemer** [comment]
@Tzahi12345 I pulled the nightly again and still have the no start issue.
```
 1: 0x7fb65fc373cc node::Abort() [/lib/x86_64-linux-gnu/libnode.so.72]
 2: 0x7fb65fc3745b  [/lib/x86_64-linux-gnu/libnode.so.72]
 3: 0x7fb65fcb9de2 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/lib/x86_64-linux-gnu/libnode.so.72]
 4: 0x7fb65fcb9f16 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/lib/x86_64-linux-gnu/libnode.so.72]
 5: 0x7fb65fc022c8 node::InitializeOncePerProcess(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]
 6: 0x7fb65fc024ac node::Start(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]
 7: 0x7fb65f170d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fb65f170e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x5569b23bc0f5 _start [node]
node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
```

**Comment by jonathanm-ur** [comment]
> @jonathanm-ur Do you still see the crash with the latest `nightly`?

Yes, exact same error strings in the logs after starting the container, followed by an immediate stop.

**Comment by GlassedSilver** [comment]
Maybe we track that error in another issue, so things are better tasked and the repo issues provide better help for manual troubleshooting as well by having (Multi-Issues / Overviews aside) one problem at a time as their concern.
