### ISSUE TITLE
[BUG] No start on latest nightly docker build

### ISSUE THREAD

**Issue by tehniemer** [Tzahi12345/YoutubeDL-Material#608]
**Describe the bug**
The container does not start.

**To Reproduce**
1. Pull latest nightly
2. Start the container
3. See error

**Expected behavior**
The container starts

**Logs**
```
 1: 0x7fb65fc373cc node::Abort() [/lib/x86_64-linux-gnu/libnode.so.72]
 2: 0x7fb65fc3745b  [/lib/x86_64-linux-gnu/libnode.so.72]
 3: 0x7fb65fcb9de2 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/lib/x86_64-linux-gnu/libnode.so.72]
 4: 0x7fb65fcb9f16 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/lib/x86_64-linux-gnu/libnode.so.72]
 5: 0x7fb65fc022c8 node::InitializeOncePerProcess(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]
 6: 0x7fb65fc024ac node::Start(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]
 7: 0x7fb65f170d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fb65f170e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x5569b23bc0f5 _start [node]
node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
```

**Environment**
- YoutubeDL-Material version
- Docker tag: nightly

**Additional context**
See #596

**Comment by GlassedSilver** [comment]
Fixed build should be up in about an hour! Thanks for the report! 👍

**Comment by Tzahi12345** [comment]
I'm not sure this error will be fixed with #607. We just handled cases where the verification of the youtube-dl binary path was causing a crash on startup. Let's keep this open for now.

**Comment by jonathanm-ur** [comment]
New pull, still crashed.

node[1]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x14a285d293cc node::Abort() [/lib/x86_64-linux-gnu/libnode.so.72]
 2: 0x14a285d2945b  [/lib/x86_64-linux-gnu/libnode.so.72]
 3: 0x14a285dabde2 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/lib/x86_64-linux-gnu/libnode.so.72]
 4: 0x14a285dabf16 node::NodePlatform::NodePlatform(int, v8::TracingController*) [/lib/x86_64-linux-gnu/libnode.so.72]
 5: 0x14a285cf42c8 node::InitializeOncePerProcess(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]
 6: 0x14a285cf44ac node::Start(int, char**) [/lib/x86_64-linux-gnu/libnode.so.72]
 7: 0x14a285262d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x14a285262e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0x55622a9500f5 _start [node]

**Comment by Tzahi12345** [comment]
I have a PR up that should fix this! See #610.

**Comment by jonathanm-ur** [comment]
Ditto, seems to be fixed.
Thanks!

**Comment by Tzahi12345** [comment]
Awesome great to hear. Thanks for the info y'all!
